# Generated by Django 4.2.5 on 2023-12-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebWater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type_bottle',
            field=models.CharField(choices=[('Large', 'Вода питьевая 5 л - 19 л'), ('Big', 'Вода питьевая 1,5 л'), ('Small', 'Вода питьевая 0,5 л'), ('Other', 'Напитки')], default='Other', max_length=30, verbose_name='Класс продукта'),
        ),
    ]
