# Generated by Django 4.2.5 on 2023-12-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebWater', '0003_alter_products_type_bottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='duties',
            field=models.CharField(default='Уточняйте информацию у администратора', max_length=300, verbose_name='Обязанности'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='requirements',
            field=models.CharField(default='Уточняйте информацию у администратора', max_length=300, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='working_conditions',
            field=models.CharField(default='Уточняйте информацию у администратора', max_length=400, verbose_name='Условия работы'),
        ),
    ]
